export {default as Home} from "./Home";
export {default as LoginRegister} from "./LoginRegister";
export {default as Routines} from "./Routines"
export {default as Activities} from "./Activities"
export {default as MyRoutines} from "./MyRoutines"
export {default as Logout} from "./Logout";
export {default as CreateRoutine} from "./CreateRoutine";
export {default as EditRoutine} from "./EditRoutine";
export {default as DeleteRoutine} from "./DeleteRoutine";